module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'components':'@/components',
                'data':'@/data',
                'router':'@/router',
                'views':'@/views'
            }
        }
    },
    publicPath:'./'
}